workspace:
  base: /go
  path: src/github.com/bennycornelissen/terraform-provider-localfile

pipeline:
  build:
    image: golang
    commands:
      - go get
      - go build

  docker_local_build:
    image: plugins/docker
    commands:
      - docker build -t terraform .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  validate_docker_image:
    image: plugins/docker
    commands:
      - docker run --rm terraform version
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  docker_push:
    image: plugins/docker
    repo: bennycornelissen/terraform-localfile
    tags: foo
    when:
      event: deployment
